server:
  port: 7002
eureka:
  instance:
    hostname: eureka2  #定义eureka实例所在的主机名称
  client:
    fetch-registry: false     #是否要从注册中心获取信息
    register-with-eureka: false  #是否要注册到eureka注册中心上
    service-url:
        defaultZone: http://admin:enjoy@eureka1:7001/eureka,http://admin:enjoy@eureka2:7002/eureka,http://admin:enjoy@eureka3:7003/eureka
  server:
    eviction-interval-timer-in-ms: 1000   #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: false #设置为false表示关闭保护模式

spring:
  security:
    user:
      name: admin
      password: enjoy